# Configuration for robot_localization
#
frequency: 50

two_d_mode: true

publish_tf: true

odom_frame: odom
base_link_frame: base_footprint
world_frame: odom
# map_frame: map

odom0: /odom
odom0_config: []
odom0_differential: false

imu0: /imu_data
imu0_config: []
imu0_differential: false
